### ISSUE TITLE
Clarify & correct the documentation license to CC BY 4.0

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes.github.io#1762]
Clause 11(f) of [the CNCF charter](https://www.cncf.io/about/charter) says:

> All documentation will be received and made available by the CNCF under the Creative Commons Attribution 4.0 International License.

The LICENSE file suggests the documentation is under the Apache license, which is presumably an oversight due to the code being under that license. (Code samples should remain under that license.)

There is no indication of the license on the actual kubernetes.io site.

- [x] Change the LICENSE to CC BY 4.0 (PR #1763)
- [x] Add a footer to all pages indicating the license, and with a link to the license (PR #1764)
- [x] Add text to the contribution process page that indicates the documentation is licensed CC BY 4.0 and all submissions will be made available under the terms of that license (PR #1765)
