### ISSUE TITLE
Pod rewrite checklist

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#649]
Join the kubernetes-sig-docs googlegroup to gain access to shared docs:

https://groups.google.com/forum/#!forum/kubernetes-sig-docs

The topics spreadsheet is here:
https://docs.google.com/a/google.com/spreadsheets/d/1PJEqLxPcbUQEBkgBEUwUivvIfYNqLkTV9878jrtWQC4/edit?usp=sharing

The template instructions are here:
http://kubernetes.io/docs/templatedemos/

The general doc editing instructions are here:
http://kubernetes.io/editdocs/

Priority 1 is Pod documentation rewrite, which involves these topics:

**Pods:** http://k8sdocs.github.io/docs/pod/ 

Running Containers in a Pod
- [ ] - 1. Using ports with containers
- [x] - 2. Defining commands and arguments in a container (container.command, container.args)
- [x] - 3. Defining container environment variables (container.env)
  - [x] Reference Secrets
  - [x] Reference ConfigMaps

// These should be surfaced in both places
Using Services with Pods (See Services)
- [ ] - Load Balancing Traffic Across Pods
- [ ] - Making Pods Externally Accessible
- [ ] - Discovering Services from a Pod

Configuring Pods for a production environment
- [x] - Configuring container restarts on failure (restartPolicy)
- [x] - Checking whether a pod can recieve traffic (container.readinessProbe)
- [x] - Checking whether a pod should be restarted (container.livenessProbe)
- [ ] - \* Allowing containers to gracefully shutdown (terminationGracePeriodSeconds)
- [ ] - Writing debug messages (terminationMessagePath, stdout logging, fluentd)
- [x] - Attaching functions to container lifecycle events (container.postStart, container.preStop)
- [x] - Assigning CPU and RAM resources to a container (container.resources)
- [ ] - *Defining a maximum execution time for a container (activeDeadlineSeconds)
- [ ] - *Configuring OS-level security privileges (Security Context)
- [ ] - *Using the host network with your container (hostNetwork)
- [ ] - **Using the host PID namespace for container processes (hostPID)
- [ ] - **Using the host IPC namespace for container processes (hostIPC)
- [ ] - Reading the host Pod metadata from a cotainer (downward api)

Configuring Pod security policies
- [ ] - Configuring access control and identities for container processes (Service Accounts)
- [ ] - Restricting the pulling of new images (container.imagePullPolicy)
- [x] - Pulling images from a private registry (imagePullSecrets)

Other:
- [x] - Explicitly scheduling a pod to a node (nodeSelector)
- [ ] - \* Preventing a pod from being scheduled on a node (nodeSelector)

**Comment by johndmulhausen** [comment]
cc @pwittrock @janetkuo

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes/issues/15244

**Comment by steveperry-53** [comment]
The specific list topics has drifted a bit from what is described in this issue. But I think we have addressed the concerns expressed here. Please reopen if you think otherwise.

See the set of topics under /docs/tasks/configure-pod-container/, starting with
[Assign Memory Resources to Containers and Pods](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/)

See the set of topics under /docs/tasks/inject-data-applications/, starting with
[Define a Command and Arguments for a Container](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/)

See the set of topics under /docs/tasks/run-application/, starting with
[Run a Stateless Application Using a Deployment](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/)

See the set of topics under /docs/tasks/access-application-cluster/. Example:
[Use Port Forwarding to Access Applications in a Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)
