### ISSUE TITLE
kubectl / CLI YAML checklist

### ISSUE THREAD

**Issue by johndmulhausen** [kubernetes/kubernetes.github.io#652]
We have a good demo of the generated YAML for kubectl being consumed by a template and rendering now: 

http://k8sdocs.github.io/docs/kubectl/

There are improvements to be made to this YAML before this goes live, however:
- [ ] A command should identify its subcommands so the template can concatenate/crosslink accordingly (example: [kubectl create](http://k8sdocs.github.io/docs/kubectl/kubectl_create/) has the subcommand kubectl create secret -- but right now that's listed as a "see also" which 404s. Subcommands are mixed with primary commands in `see_also:` from what I can tell. ) 
- [ ] There should be a field in the YAML for "example command" that shows the command in action.
- [ ] The docstrings should support Markdown so that linking and formatting can occur. For example, on [kubectl replace](http://k8sdocs.github.io/docs/kubectl/kubectl_replace/), the top area has URLs that should be hyperlinked, example commands that should be `monospaced`, DEPRECATED notices that should be bold, etc. 
- [ ] Various docstring improvements. http://k8sdocs.github.io/docs/kubectl/kubectl_replace/ has sentences that don't start with an uppercase letter, poor/overly terse writing, etc. 
- [ ] Since the template for consuming this CLI YAML has been made, we might as well produce this YAML for the other tools, namely: kube-apiserver, kube-proxy, kube-scheduler, kubelet, and kube-controller-manager

cc @lavalamp @pwittrock

**Comment by lavalamp** [comment]
Thanks for the report.

**Comment by jaredbhatti** [comment]
Outdated issue.  Closing.
